### ISSUE TITLE
Guide on how to build ?

### ISSUE THREAD

**Issue by vknecht** [stayboogy/stayboogy_lineage13_idol347#1]
Could you please provide details about how to build with this tree,
especially wrt. repo/repo init and the manifest ?
TIA

**Comment by vknecht** [comment]
For the records, I was able to build it on Fedora 33 using this :

```
git clone https://github.com/stayboogy/stayboogy_lineage13_idol347.git
cd stayboogy_lineage13_idol347/
repo init -u https://github.com/LineageOS/android.git -b cm-13.0

====================================================================================
export LC_ALL=C
export USE_CCACHE=1
export CCACHE_COMPRESS=1
export ANDROID_JACK_VM_ARGS="-Dfile.encoding=UTF-8 -XX:+TieredCompilation -Xmx8G"

# Download Java 7 from Oracle, or use a distro which still provides Java 7 JDK/SDK...
export JAVA_HOME=$HOME/apps/jdk1.7.0_80
export PATH=$JAVA_HOME/bin:$PATH

# Might help getting rid of some compat errors
export JAVA_1_4_HOME=$JAVA_HOME

# Provide missing dtbToolCM
# mkdir -p out/host/linux-x86/bin
# Download https://github.com/vknecht/android_kernel_alcatel_msm8916/raw/hybris-14.1/tools/dtbToolCM
# and copy it in out/host/linux-x86/bin
# and make sure it's executable, eg. with chmod +x out/host/linux-x86/bin/dtbToolCM

# Use Python 2 instead of Python 3 to prevent this error with event_log_tags.py :
# TypeError: cannot use a string pattern on a bytes-like object
# export PATH=$HOME/.local/bin/:$PATH
# where $HOME/.local/bin/python is a symlink to python2

# Use prebuilt maven so that it works with JDK 7
export PATH=$PWD/prebuilts/eclipse/maven/apache-maven-3.2.1/bin:$PATH

# Fix Return code is: 501 , ReasonPhrase:HTTPS Required
# Add this block to <mirrors> in prebuilts/eclipse/maven/apache-maven-3.2.1/conf/settings.xml
#    <mirror>
#      <id>central-secure</id>
#      <url>https://repo.maven.apache.org/maven2</url>
#      <mirrorOf>central</mirrorOf>
#    </mirror>

# Fix "Received fatal alert: protocol_version" (aka https/TLS protocol version error)
export MAVEN_OPTS="-Dhttps.protocols=SSLv3,TLSv1,TLSv1.1,TLSv1.2 -Djdk.tls.client.protocols=TLSv1,TLSv1.1,TLSv1.2"

# Fix curl/Jack error: https://surepy.github.io/My-ArchLinux-and-LineageOS-13-0-building-Experience/
# curl: option --no-proxy: used '--no-' for option that isn't a boolean
# curl: try 'curl --help' or 'curl --manual' for more information
# ERROR: Communication error with Jack server (2)
export ANDROID_COMPILE_WITH_JACK=false

# Fix yylloc error
# Mod these two files to add "extern" instead of deleting them like in
# https://review.lineageos.org/c/LineageOS/android_kernel_oneplus_sm8150/+/273023

# Fix some error about scripts/Makefile.build:309 : scripts/mod/empty.o] Erreur 126
chmod +x $PWD/kernel/alcatel/msm8916/scripts/gcc-wrapper.py

# Fix proguard errors
# Modify the following files to read LOCAL_PROGUARD_ENABLED := disabled
# packages/services/WeatherService/Android.mk
# packages/services/LiveLockScreenService/Android.mk
# packages/apps/Trebuchet/Android.mk
# packages/apps/Messaging/Android.mk
# packages/apps/Eleven/Android.mk
# and set DISABLE_PROGUARD
export DISABLE_PROGUARD=true


source build/envsetup.sh
croot
brunch idol347
```

**Comment by tenzap** [comment]
Do you think this will work with lineageos 15.1 for idol 3 4.7? There is [this project](https://github.com/CarlosArriagaCM) for idol 3 5.5 that works with 15.1.

**Comment by vknecht** [comment]
Most probably not, since it didn't really work on idol3 anyway (sluggish, hot temperature, ...).
However, idol347 (idol3 too) has relatively good support with close-to-mainline kernel now
and it's working with postmarketOS :
https://wiki.postmarketos.org/wiki/Alcatel_Idol_3_4.7%22_(alcatel-idol347)
So the fancy project would be to start a mainline Android port, with a much more
recent version than Oreo/15.1 :-)

**Comment by tenzap** [comment]
Thanks for your answer. Interesting projects/ideas :)

**Comment by vknecht** [comment]
Also, postmarketOS has a Waydroid package which "emulates" LineageOS 17.1 (atm),
only quickly tried it on idol3 without additional apps tho, so couldn't say how good it is
but it ran fairly well even without all 8 cores nor full speed.
Join postmarketOS channel if you're interested :-)

**Comment by tenzap** [comment]
I would prefer to stay with Android actually because the device is still used daily.
Would it work better if lineage os were built in its 'go edition' which is designed for such devices with<= 1gb ram? I may give it a try. Hopefully it won't be difficult to upgrade to Oreo 8.1. Go edition appeared with Oreo.

**Comment by vknecht** [comment]
afaik, getting Oreo or Go requires 3.10 vendor kernel upgrades to support Android 8 features,
which is what Carlos tried and didn't work so well. So Go doesn't make a different at this point.
I think Go is only lighter on userspace side.

**Comment by tenzap** [comment]
I managed to build a ROM of lineage 15.1 with 3.10 kernel for idol347 but it doesn't boot. There is only the splash screen with black background. Would you help me in meeting this work? Should I switch to XDA to further discuss it? I also built 15.1 for another device (Sony and it users 3.10 kernel too on another soc: 8226) based on http0://f2065.ru custom ROM

**Comment by vknecht** [comment]
There are tons of potential problems in such a project...
One good first step would be to get logs, provided the device is alive enough to send some, or you have uart access...
I don't know too much about Android, but I have my doubts about being able to run Oreo without kernel backports.
For example, see what Carlos did for idol3, especially wrt. binder:
https://github.com/CarlosArriagaCM/android_kernel_alcatel_msm8916/commits/lineage-15.1
Probably you'd have better luck trying with this kernel and branch since it at least was booting,
tho you'll have to adapt things (eg. defconfig) for idol347, whose vendor kernel was arm32 iirc,
which might be a problem, or not.
Then the devicetree will probably require mods too:
https://github.com/CarlosArriagaCM/android_device_alcatel_idol3/commits/lineage-15.1

Frankly, it's quite a mess, which is why I prefer starting from a clean state with mainline kernel :-)
Feel free to ping me from xda and/or github (or whatever git forge you'll use)

**Comment by tenzap** [comment]
Thanks.

For debugging I don't know how to check if the kernel gets loaded on the phone. Could you point me to where to look at for this ? I'm able to enter recovery (twrp 3.1).

No uart access. 

I just tried building with mainline Linux 5.15 but it now requires GCC 5.1 while lineage seems to builds with 4.9.
So I used 5.14.21 and building failed because of missing headers...

I will try with the repo you point to.

Otherwise, maybe I will also try with lineage 17.1 (by enabling Android go edition) + linux 5.14, that would at least fix some missing headers.

**Comment by vknecht** [comment]
I don't think you can jump like that to mainline kernel in an outdated build environment.
GloDroid seems to be a nice one for AOSP, so I opened an issue there GloDroid/glodroid_manifest#180
to see how to proceed.
There seem to be a "low-ram" define/flag which should help for idol347.
Probably getting modern LineageOS will be easier after we get this working.

As for checking if kernel boots, one way is to force panic/reboot by modifying kernel,
eventually also getting logs from pstore in twrp, provided the idol347 build has that
(had to do that for idol3 and modify twrp img to include a kernel with pstore enable).

**Comment by tenzap** [comment]
I could build the idol347 device tree of Stayboogy (that I had to patch) using the kernel of Carlos (and with the idol347 defconfig of Stayboogy) that needed 5 small patches.

However I don't have access to the device right now, so I can't test. If you are interested I can share the ROM. No idea if this would work. It is lineage-15.1 in the "Go Edition".

**Comment by vknecht** [comment]
https://forum.xda-developers.com/t/idol3-idol347-the-future.4434721/

Not the idol347 (didn't try yet), but still...
![Screenshot_20220420-212858](https://user-images.githubusercontent.com/12055518/164337506-cb48e120-6fa2-40c1-b32f-92def283bbaa.png)

**Comment by stayboogy** [comment]
Sorry for never replying to this...

My device tree is for such an old build it will need heavy modifications to bring it into compliance with current builds.  Both the device tree and the kernel source will have to have upstream additions and reconfiguration in order to get a buildable source.

I have virtually abandoned this device and anything Google based basically.  Google is the worst entity in the world and their operating system sucks so bad I will never use an Android device again as my daily driver.  The platform just plain sucks now.

**Comment by vknecht** [comment]
@tenzap @stayboogy 
Finally posted the [[ROM] AOSP for idol3 & idol347 with (close-to) mainline kernel](https://forum.xda-developers.com/t/rom-aosp-for-idol3-idol347-with-close-to-mainline-kernel.4533061/)...
There's also https://wiki.postmarketos.org/wiki/Alcatel_Idol_3_4.7%22_(alcatel-idol347)
with less Google and more features :-)
